### ISSUE TITLE
Secure boot ETA?

### ISSUE THREAD

**Issue by darkbasic** [Drive-Trust-Alliance/sedutil#109]
Hi, I find SED quite useful but I don't trust it that much, so I also would like to use cryptboot together with software encryption to protect against Evil Maid attacks. This obviously require to enable Secure Boot, which is not currently supported by sedutil. So I would like to know if you ever intend to support it (or if there are reasons because it will never get implemented) and, eventually, if you have an ETA for it.

Thanks,
Niccolò

**Comment by r0m30** [comment]
Hi,
If our authenticode cert provider was in the default list of CAs for UEFI we could easily support Secure Boot, but Microsoft is only root CA for UEFI (why I don't know) and there is zero chance of them signing our code. To support Secure Boot we would have to document how to add another root certificate to your computers bios and since every vendor is different that would be a huge if not impossible task.  There would also be recovery issues if the bios was reset by the user or a dead battery.  

Secure Boot is something that I would be interested in supporting but I don't have any ETA or even an assurance that it will ever happen, sorry.
