### ISSUE TITLE
Unlocking the secondary drive?

### ISSUE THREAD

**Issue by Jm3LZeT** [Drive-Trust-Alliance/sedutil#110]
I have two identical drives using the same SID and Admin1 passwords.  Everything works.  If I change the SID and Admin1 passwords on the secondary drive Windows starts but then hangs during boot.  Is this normal?  Do the passwords have to be the same on both drives to work properly?

Also, when running "--initialsetup" on the secondary drive MBRDone and MBREnable are set to ON.  Should these settings be turned back OFF for the secondary (non-boot) drive?

**Comment by r0m30** [comment]
Yes, the PBA uses the same password to unlock all OPAL drives on the machine.  If you change the password on the second drive it is not going to unlock.

You can set MBREnable off if you want to but Windows has a hard time with locked drives where the Shadow isn't enabled because it gets errors when it tries to access the drive.
