### ISSUE TITLE
Mac EFI still first boots to PBA after --setMBRenable off

### ISSUE THREAD

**Issue by Teutone** [Drive-Trust-Alliance/sedutil#136]
First I'd like to thank all devs working on sedutil for your hard work on an open-source implementation of OPAL managing software.

I tested sedutil on my triple boot [MacOS Sierra,Debian Stretch,Windows10] Macbook White (Early 2009) with a Samsung 850 Pro SSD - and managed to set up OPAL from Debian; after enabling the ShadowMBR and shutdown, the UEFI PBA asks for a password as expected. Afterwards it reboots to refind; so I'm still able to organize the multi-boot-environment. 

Now after using the commands from the wiki to disable the ShadowMBR
```
sedutil-cli -–disableLockingRange 0 <password> <drive>  
sedutil-cli –-setMBREnable off <password> <drive>
```
I still get a double boot after shutdown. The Macbook boots to a black screen for a few seconds, doesn't prompt for anything but reboots shortly after. Then refind boot manager appears. I cleared the Mac's EFI entrys using efibootmgr from Debian to no avail. 

Any clues? If you need any additional information to debug I'd be happy to help.

-13Teutone13

**Comment by scottcmarks** [comment]
Teutone -

Did you power-cycle the SSD?  Since it's the main drive for your Macbook,
you would at the least need to do a complete shutdown.  If you get the same
unexpected result, try shutdown, remove the battery for 30 seconds while
holding the power button, replace the battery, try again, and report those
results.  Please include the results of sedutil-cli --query <drive>.

It's a bit fortunate that you're on a Macbook white with the replaceable
battery so that this can be tested -- with the later Macbooks, "power down"
is always a matter of guessing.

I'm hoping that the answer is just an ordinary power-down, by the way --
taking out and replacing the battery is certainly not something one would
want to do very often.

Best,
Scott

**Comment by gomoku** [comment]
> First I'd like to thank all devs working on sedutil for your hard work on an open-source 
> implementation of OPAL managing software.

Where do you see this hard work?
- last change/ pull / commit 11 months ago --> https://github.com/Drive-Trust-Alliance/sedutil
- 9 pulls waiting over 11 months--> https://github.com/Drive-Trust-Alliance/sedutil/pulls
- ancient documentation on wikis not updated since ages

Not mentioning the app is full of bugs, for example:

- can't change my password from 9 char to longer, thus my actual password remains weak, because sedutil can't unlock drive on PBA after password change on Windows --> 
https://github.com/Drive-Trust-Alliance/sedutil/issues/114

- can't even boot now --> https://github.com/Drive-Trust-Alliance/sedutil/issues/46

Developement of sedutil scares me.

**Comment by kylemanna** [comment]
> Where do you see this hard work?

Woof, the Internet has no shortage of ungrateful people.  You're always welcome to fix bugs yourself on your own fork if the pull requests don't see any action.

**Comment by gomoku** [comment]
Woof, the Internet has no shortage of homos. Constructive criticism does not immediately mean ungratefulness, you homo. I AM grateful but only average, just not so much to say "I love sedutil and your 'hard work' on it, especially these annoying bugs/pulls/documentation not being fixed/accepted/updated almost a year". I AM greatful for work but I wouldn't call it hard work, and even with a medium work, there shouldn't be so much so longely unfixed/unaccepted/outdates bugs/pulls/docs. And why are you even telling me about fixing bugs by myself? I haven't ordered anyone anywhere to fix bugs nor to develop sedutil, they may remain unfixed another year or so, I don't care, I just have expressed my opinion and stated facts, which is called a constructive criticism, not an ungreatfulness, you homo. You are like sensitive/ soft beautiful woman which if she doesn't get another compliment, she will cry, and call ungreatful everybody around.

**Comment by cristim** [comment]
I propose we calm down the tone of this discussion, stop calling names and let's try to come to an agreement, in the best interest of this software and the user community.

I'm also not happy about the state of the open source project, I'd like to see some of the PRs merged and not need to use unofficial forks of random individuals. I also don't like the fact that the last commit in the official repo was almost a year ago and that there are lots of unsolved bugs and a growing list of issues.

Recently I also contacted DTA on twitter about the state of this project and got a kind of answer, apparently they try to implement major features as paid support requests: https://twitter.com/thedrivetrust/status/866284834867511297

My proposal is to try to fork the project and govern it as a normal, meritocratic open-source project, by the community in the interest of the community. We can look at the current forks, pick the most evolved one as a starting point and give anyone with enough contributions power to steer it forward, and try to merge the pull requests once they pass code review.

Unfortunately my time is limited and my C++ skills and domain knowledge are close to nil (I usually write code in other languages), but I can set up the initial project infrastructure and delegate permissions to more experienced developers like the most prominent fork authors. I guess there may be people out there able to do code reviews and help the community, but not willing to take this kind of maintainer role.

**Comment by cristim** [comment]
The project was forked at https://github.com/sedutil/sedutil under a new Github organization

I also set up a gitter chat room at https://gitter.im/sedutil/Lobby which can be used to communicate in real time with the community

**Comment by r0m30** [comment]
After you do the setmbrenable off does a query show it as off?  When you powercycle the machine what does a query show?
