### ISSUE TITLE
Keyboard not Working

### ISSUE THREAD

**Issue by dtodto** [Drive-Trust-Alliance/sedutil#179]
Hello Guys,
I have an Fujitsu U 757 Notebook and using the UEFI 64 Image.
It loads via USB-Stick but I can't use the keyboard. No Login possible..

Do you know how to fix this issue?

Thx in advance,
BR Daniel

**Comment by cristim** [comment]
The kernel running on the PBA image may be missing some drivers.

You can use your usual Linux distribution to see how is the keyboard connected or which drivers it needs. It may be that you have an exotic USB controller or something like that.

**Comment by dtodto** [comment]
Thx, I was able to use 1.15 - Keyboard is working with this version..

But whats interesting is that longer PW (longer than 10 char) and/or including special/special character ($) were not working!!

I've used now a shorter PW (8 char) and do not use $-char. That works fine..

BR Daniel

**Comment by cristim** [comment]
I sometime notice that the keyboard is not yet ready to take input when the password prompt is shown, and the first few characters are lost and the password fails to unlock the drive.
Unfortunately the PBA will reboot the machine after an incorrect password, so I eventually got used to wait for a few seconds or type a few random chars until I get input from it, then I erase them all and start entering my actual password.

It would be nice if the PBA would wait for the keyboard to initialize and ask for the password a number of times instead of rebooting the computer right away.

**Comment by lellis1936** [comment]
> I sometime notice that the keyboard is not yet ready to take input when the password prompt is shown, and the first few characters are lost and the password fails to unlock the drive. Unfortunately the PBA will reboot the machine after an incorrect password, so I eventually got used to wait for a few seconds or type a few random chars until I get input from it, then I erase them all and start entering my actual password.
> 
> It would be nice if the PBA would wait for the keyboard to initialize and ask for the password a number of times instead of rebooting the computer right away.

Yes and my experience is sometimes it will not accept input no matter how long you wait.  In this scenario a computer reset or power cycle is sometimes required.  No esoteric keyboard here, just an old-school desktop system with a PS2 keyboard.
