### ISSUE TITLE
OPAL FAILED - PBA v1.51, Samsung 960 Pro NVMe, UEFI64

### ISSUE THREAD

**Issue by Kono14** [Drive-Trust-Alliance/sedutil#180]
I have this system:
MSI Z270 Gaming M5
 - newest UEFI version installed (v1.70)
- UEFI boot only (legacy off)
- secure boot off, fast boot off, no CSM option
Samsung 960 Pro with firmware 2B6QCXP7, in m.2 slot #2
Windows 10 Pro x64

I follwed the instructions from this wiki carefully: https://github.com/Drive-Trust-Alliance/sedutil/wiki/Encrypting-your-drive
- flashed the rescue system to USB
- checked my drive is indeed OPAL ready
- all commands run through without problems
- the 2nd try with "linuxpba" it shows = **is OPAL Unlocked**

But then I cut the power (poweroff command + switch of). When I try to reboot my UEFI menu doesn't regonize the SSD at anymore. It shows no device found in m.2 slot. As a consequence, the installed PBA also doesn't boot. 

When I boot the rescue USB stick again, it still is able to find the SSD (even though it's not listed in UEFI menu). When I run the command "linuxpba" again now it shows = **is OPAL Failed**
- unlocking, setmbrdone off & relocking, setmbrdone on = still the same

Complete revert and remove of OPAL with the 3x commands described here: https://github.com/Drive-Trust-Alliance/sedutil/wiki/Remove-OPAL
- all commands run through without problems, my SSD gets recognized in UEFI menu again, no data loss

I really don't understand what's going wrong.

**Comment by maletor** [comment]
I have the same issue with 960 Pro. I couldn't get a password prompt after following the instructions exactly.

**Comment by Kono14** [comment]
There seems to be no help and no solution. I just ended up using Windows Bitlocker software encryption, the performance loss is surprisingly really small, as you can see here:

![crystaldiskmark_v6_960pro_512gb_bitlocker](https://user-images.githubusercontent.com/2979956/33601805-99404796-d9ad-11e7-8e7b-5fe1d4d5c655.PNG)

**Comment by kasperlewau** [comment]
I'm on my third day attempting to set myself up with hardware encryption.  

Machine: XPS 13" 9360
SSD: 960 EVO NVMe
PBA: UEFI_64.img
BIOS: UEFI-Boot, No legacyboot, No fastboot, No secureboot.

--- 

Setting up the encryption itself does not seem to be an issue on my end, nor the decryption process (from the Rescue USB). 

The problem is getting the 'Shadow MBR' to showup as a bootable option. I've had a go at the following to forcefully add it: 

```
1 # poweroff
2 # boot
3 # F12 -> select Arch Live USB
4 # mount /dev/nvme0n1 /mnt
```

After step(4), I get a _slew_ of GPT range errors. I respectfully ignore them and move along.

```
5 # ls -l /mnt/EFI/boot 
```

At step(5), I can verify that I have `syslinux.cfg`, `bootx64.efi` and a couple of other files in the shadow MBR. I tried to edit `syslinux.cfg` to increase the loglevel from 0 to 9, but to no avail. Writing to the file causes the same GPT range errors (along with some other friends - IO errors, primarily) to come rushing in, corrupting the display of my `vim` buffers. And to top it off - the filesystem is readonly. _Moving along._ 

``` 
7 # efibootmgr -a -L "shadow" -l "\EFI\boot\bootx64.efi" -d /dev/nvme0n1
8 # reboot
``` 

Upon rebooting, I can see the `"shadow"` option (UEFI). Booting into it, I land at a place that looks something like this; 

``` 
WARNING: No config loaded. 
Boot: _
```

At this point, it seems to me as though I screwed up the `efibootmgr` entry. And so I have another go; 

```
9 # efibootmgr -a -L "shadow" -l "\EFI\boot\bootx64.efi"
``` 

Dropping the pointer to the specific drive (`nvme0n1`), I reboot & give it another whirl. Now, instead of getting dropped into no-config-land, I end up in my live boot Arch USB. 

--- 

Days 1 & 2 were spent trying out the different PBA's off of the Rescue image (`BIOS32`, `UEFI64`) on a **non-empty** system. That is to say, I attempted to put the hardware encryption in place _after_ having done my initial installation of Arch Linux + systemd-boot (& later, switching over to `grub`). 

Having scoured through the issue boards of the various `sedutil` repos, I feel as though the bulk of us are setting up hardware encryption _after_ installing our OS of choice. 

This did not appear to make any sort of real difference at the end of it all. I am still stuck in a place where I can unlock the NVMe drive _through_ the Rescue USB and then access the drive as per usual. I cannot however, boot into the PBA on the NVMe drive itself. I'm probably mixing all of these pieces up, it's been a long three days.. 😓 

---

I'm at a loss whether the OS or the Opal encryption should go first, whether I should be looking at `grub`/`systemd-boot` or another, whether this is a Dell UEFI issue in its entirety or if I'm simply screwing up the `efibootmgr` calls. 

I'll keep trying & reading what little resources are out there. Should anyone stumble upon this and have a pointer or two for the given setup, I'd love to hear em!

**Comment by kasperlewau** [comment]
Following up on my previous comment: 

I have successfuly booted into the PBA and unlocked my drive by switching the `SATA Mode` from `AHCI` to `RAID On`. I'll see if I can make my Arch installation work with this, all the while the wikis suggest _it will not_ work in Arch.

That is to say, after unlocking the PBA I get dropped into the next available boot option - the unlocked NVMe drive is not bootable in `RAID On` as it stands.

**Comment by hotchkiss87** [comment]
@kasperlewau this happened to me on the Precision 5520 awhile ago. The XPS has the same frame and similar parts, so it might be the same issue.

The issue is that REFIND/efibootmanager doesn't work well with the Dell BIOS- the Dell BIOS I believe ignores a lot of things.

It's not that bad though- I just manually added an option for PBA in the BIOS boot menu (hit 'f12' on the dell logo on startup, and add it manually there.) After I booted through the PBA, I also had to add options for my Windows and GNU/Linux partitions through the Dell BIOS menu again too.

**Comment by kasperlewau** [comment]
@hotchkiss87 

I gave it another whirl just now with the UEFI64 image and I can't quite figure out how to add the manual entry for the PBA. 

The only time I get access to the FS contained in the PBA is when SATA mode is set to "Raid ON". If not, I can't get a pointer to that filesystem (this is all from within the BIOS Setup (F2)) and so I cannot setup a manual boot entry. 

If the SATA mode is set to Raid ON - I am dropped into a no-config state of what I think is syslinux. 

I've disabled the MBR & lockingrange for now.

**Comment by r0m30** [comment]
As @hotchkiss87 said, this is an issue with how you bios searches for bootable images, the best solution is usually to change the pba EFI partition layout to match your linux EFI partition layout

**Comment by CySlider** [comment]
@r0m30 your idea sounds extremely promising.

Any hint as of how to do that, would be appreciated though. I'll try to solve it on my own as well. If I find out how, I will post the result here.

**Comment by polortiz4** [comment]
@r0m30 How would one go about doing that?
