### ISSUE TITLE
Booting & unlocking USB attached SSD

### ISSUE THREAD

**Issue by eleksis** [Drive-Trust-Alliance/sedutil#183]
Hi,
was struggling to get sedutil working on my external bootable ssd.
HW: Samsung evo 850, Startech with ASM1051E chip, Lenovo T460.

I followed commands on wiki. (disk detected, locking enabled, mbr loaded, etc)
The problem was, when i entered password at PBA, it kept re-loading shadow mbr and asking me for pwd again and again.

After setting setMBRDone to off, problem seems to be gone. What exactly does this do?
Documentation is really poor.

**Comment by elpetak** [comment]
I'm just guessing but I tihnk USB is probably losing power on reboot and that re-locks the drive. Maybe you need external power for the USB drive.

**Comment by r0m30** [comment]
Setting mbrdone off????????  maybe you mean on?
It is probably a power cycle issue as @elpetak indicated above but if toggling the mbrdone flag fixed it then that is strange because the drive should be locked/encrypted if there was a power cycle.

I don't and won't document the OPAL spec, only sedutil.  IF you want to know what mbrdone or any other OPAL flag or feature is/does there are hundreds of pages on the TCG website that go into great detail about those.
