### ISSUE TITLE
Booting from UEFI64: missing rcS

### ISSUE THREAD

**Issue by juliandroid** [Drive-Trust-Alliance/sedutil#24]
I've built on my machine the UEFI64 image and used it as PBA on my SSD.

When I'm booting from it I get the following error:

> can't run '/etc/init.d/rcS': No such file or directory

Apart from that I also get "/sbin/linuxpba: error while loading shared libraries" reported in the #21 

After getting a root shell I have verified that the /etc/init.d/ is empty, so I have no idea where the "buildUEFI64" failed and why rcS is missing.

Do you have any ideas?

**Comment by r0m30** [comment]
The build didn't fail, that was deleted because there is no need for it,  I don't know why it is still trying to execute it. 

I think with the many issues you are having with building the images the only way you are going to be able to consistently build them is to create packages for linuxpba and sedutil-cli so they are built by the buildroot process.  take a look at cranderson/buildroot-linuxpba on GitHub for an example.

**Comment by r0m30** [comment]
This should be fixed in v1.15
