### ISSUE TITLE
can sedutil be used with partition ?

### ISSUE THREAD

**Issue by ranshalit** [Drive-Trust-Alliance/sedutil#268]
Hello,

Is it possible to use one partition as unlocked and another as locked ?
Is it possible to put the PBA in the unlock partition ?

Thank you,
Ran

**Comment by alexisfrjp** [comment]
I've already tried to have partially locked area on Linux. That doesn't work well at all.
The kernel is searching again and again and testing all the bytes one by one.
Also if you hide properly a single partition, the partitions table will be corrupted because the OS will try to find something but keep receiving read/write errors (it seems the drive responds with errors instead of accepting a read of 0)

I've tried almost everything from locking only the partition to the partitions table to read only locking, nothing has worked.

If you find the solution, please share.

**Comment by rdaysky** [comment]
@alexisfrjp Have you tried addpart(8)? Your partition table could only contain references to unprotected partition(s), and the code that unlocks protected ones could also insert the data into the kernel’s idea of the partition table.

**Comment by alexisfrjp** [comment]
I don't see how you want to do that. I'm not willing to change the kernel module and that won't work with windows.

Could you explain a bit more? I haven't tried this method.

**Comment by rdaysky** [comment]
@alexisfrjp If the problem is that Linux attempts to read the partition (to discover LVM volumes and whatnot) but the drive responds with read errors and Linux hates that (is that the case?), then here’s a possible way forward:
1. Don’t have a partition in the partition table, but note its location on the drive and store that in the initramfs.
2. Kernel doesn’t attempt to read it, because it doesn’t know that it exists.
3. Initramfs asks user for the decryption password and decrypts the locking range.
4. When that succeeds, initramfs runs addpart(8) to add the partition to the kernel’s view of the drive, but not to the partition table on the drive.
5. The partition can now be read. The usual mechanisms discover LVM or whatever the partition could contain.

A more robust solution would be to designate a specific GPT partition type for this case and to make sure neither the kernel nor udev try to read data from partitions of that type unless specifically instructed to.

No idea regarding Windows.

**Comment by alexisfrjp** [comment]
Now I see what you mean. For my case, I wanted to use the drive as an external drive (more like usb drive) with a public and a private partitions I could plug in random computers, not only specific ones.
But your solution can be worth a try!
