### ISSUE TITLE
m4 requires a patch to update it to the newest glibc

### ISSUE THREAD

**Issue by maenpaa24** [Drive-Trust-Alliance/sedutil#285]
Hi!

The package m4 needs a patch to meet the new glibc requirements. It has not been done officially so one has to do it manually. How should one modify the source code so that the patch is applied automatically?

The patch can me summarize to execute this inside the m4 folder:

sed -i 's/IO_ftrylockfile/IO_EOF_SEEN/' lib/*.c
echo "#define _IO_IN_BACKUP 0x100" >> lib/stdio-impl.h

Info gathered from http://www.linuxfromscratch.org/lfs/view/development/chapter06/m4.html

**Comment by maenpaa24** [comment]
you can delete this issue

**Comment by oom-is** [comment]
I think you've seen other relevant traffic, but just in case:  The m4/glibc issue you've noted is due to an outdated Buildroot target from 2017.

Please take a look at my "[integ](https://github.com/oom-is/sedutil/tree/integ)" branch ([latest binary releases](https://github.com/oom-is/sedutil/releases/tag/v1.16-beta1)) or in @ChubbyAnt's [fork](https://github.com/ChubbyAnt/sedutil) ([latest binary releases](https://github.com/ChubbyAnt/sedutil/releases/tag/1.15.1-44)), both of which use an updated Buildroot target (2019.02.6 LTS) and an updated Linux kernel (4.14.146 in the 4.14 LTS series).  

ChubbyAnt's releases/tree are only tested on NVME+Windows, while mine are tested on Windows&Linux but primarily SATA.  If these don't fix your issues then please follow up.

NOTE that both of these forks also use SHA512 for password hashing, which means they're not backward compatible with 1.15.1 "vanilla".  You'll need to uninstall (actually revert, preferably `--revertnoerase` then `--revertTPer`) the DTA 1.15.1 SEDutil before attempting to install the updated SEDutil PBA.
