### ISSUE TITLE
Computational cost of the key derivation function

### ISSUE THREAD

**Issue by christoph-schneegans** [Drive-Trust-Alliance/sedutil#286]
Hello there!

I have been using sedutil for about two years with my Samsung 850 EVO SSD, and I have just become a patron for the Drive Trust Alliance on patreon.com.

One thing that bothers me is how quickly the drive is unlocked, which means that the key derivation function runs rather fast. Is there a way to increase the computational cost of the key derivation function? I personally would not mind waiting for 5 seconds for the drive to unlock.

Regards
Christoph

**Comment by ladar** [comment]
@christoph-schneegans I was concerned to. Which is why I created a fork that uses [SHA512](https://github.com/ladar/sedutil/releases) instead of SHA1. If you want to be extra sneaky, just increase the `75000` found [here](https://github.com/ladar/sedutil/blob/master/Common/DtaHashPwd.h#L46) and recompile.

Or if you'd prefer, I can post a recovery image that uses a higher number of hash iterations. Just beware, the SHA512 and/or image with a custom hash round won't be compatible with an existing configuration. You'll need to completely remove OPAL using a compatible recovery image, before booting the more secure version, and configuring the drive anew.

**Comment by r0m30** [comment]
I have gotten way more complaints about how long the hash takes than that it's not strong enough.
We are doing a one way salted hash of the password, and I know of no credible claims that a salted SHA1 hash can be reversed.  The salt is unique to each drive so no prebuilt table can be used.  The attacker would then be limited to the retry limit for the ADMIN1 user (usually a single digit number) before requiring a power cycle of the drive.  If your disk was confiscated by a state actor then they could do this in their lab but at that point I think it is far more likely that they would attack the drive firmware to extract the keys.
