### ISSUE TITLE
Doesn't unlock

### ISSUE THREAD

**Issue by parkinsonp** [Drive-Trust-Alliance/sedutil#294]
I have tried the windows executable and it doesn't unlock. I have tried multiple systems, brands of SED. The password works following the wiki but when it boots it doesn't unlock. I have taken pictures to make sure I didn't have fat fingers, etc. I seem to be missing something.

**Comment by oom-is** [comment]
I had similar issues with the pre-built Windows executable - I was able to use the rescue Linux image from a thumb drive and due to other limitations I've not spent any time trying to build Windows executables from other forks.  There are several forks mentioned in the comments on Issue #292 that are more up-to-date so you might have luck with building Windows executables from those.  Good luck.

**Comment by oom-is** [comment]
Any chance you're using a Ryzen chip?  There are some (r0m30-)documented issues with Ryzen chips ( issue #242 ) that are fixed in ChubbyAnt's fork ( [https://github.com/ladar/sedutil/issues/5](url) https://github.com/ChubbyAnt/sedutil/issues/1 ).  That fixed most of the issues I was having under Windows on a Ryzen chip/mobo combo.

**Comment by oom-is** [comment]
If you have further interest in pursuing, @ChubbyAnt has a [fork with compiled binaries](https://github.com/ChubbyAnt/sedutil/releases/tag/1.15.1-44) he's supporting which is primarily focused on Windows+Ryzen+NVMe but untested on Linux and likely not much on SATA.  Meanwhile I have a similar [fork with compiled binaries](https://github.com/oom-is/sedutil/releases/tag/v1.16-beta1), tested on both Windows and Linux and including both Ryzen support and similar NVMe patches - but those binaries are mostly (at this point) tested using SATA drives.

_NOTE that both of the above forks are using SHA512 in place of SHA1 for the unlock credentials....so there's no backward compatible way to use one of these with a drive that was initialized using "vanilla" DTA SEDutil 1.15.1.  If you'd like we can talk through how to revert etc._

One or the other of these forks might be useful.  Also, feel free to post more details about what systems, what brands of SED, exactly what else you've tried, etc.  GLHF.
