### ISSUE TITLE
Smasung 970 Pro NVMe

### ISSUE THREAD

**Issue by Zetanova** [Drive-Trust-Alliance/sedutil#314]
I used sedutil-cli successfuly for many Samsung SSD models under windows.
Few times there where only some bugs with drivers. 

But i could never get a Smasung NVMe to work.
It is always listed with no opal support. 
I tried the windows nvme driver and all samsung nvme up to 3.2

Is this a sedutil-cli, driver or firmeware issue?

under windows:
sedutil-cli --scan
Scanning for Opal compliant disks
\\.\PhysicalDrive0  2  KINGSTON SUV500120G                      003056RI
\\.\PhysicalDrive1  2  Samsung SSD 860 EVO 1TB                  RVT02B6Q
\\.\PhysicalDrive2  2  Samsung SSD 860 EVO 1TB                  RVT02B6Q
\\.\PhysicalDrive3 No  Samsung SSD 970 PRO 512GB                1B2QEXP7
\\.\PhysicalDrive4 No  Samsung SSD 970 PRO 512GB                1B2QEXP7 

A hint would be appreciated.

**Comment by oom-is** [comment]
This is a fault in DTA official "vanilla" SEDutil which does not formally support NVMe devices under Windows (and unfortunately is lacking updates since 2017).  Please feel free to take a look at the [precompiled binaries in my fork](https://github.com/oom-is/sedutil/releases), or the [original lukefor fork](https://github.com/lukefor/sedutil/tree/windows_nvme) from which I sourced the Windows NVMe patch, or [ChubbyAnt's fork](https://github.com/ChubbyAnt/sedutil/releases) also derived from @lukefor's code, for binaries that do support NVMe on Windows.

As a first step, you could also take the Linux64 Rescue disk image from here (or the corresponding image from my releases or ChubbyAnt's, or the Rescue ISO image I created) and put it onto a USB or CD so you can boot the Linux rescue disk.

NOTE that at least mine and @ChubbyAnt's use SHA2/SHA512 for hashing the user auth password that is stored to the drive, so they are NOT backward compatible with a drive that was previously managed/encrypted by "vanilla" DTA SEDutil 1.15.1.

Please drop a line in this thread with follow-ups, and I'll try to keep an eye out.

**Comment by Zetanova** [comment]
Thank you for the informative message and your work.
I dont know why, but i stopped looking into forks long time ago.

I will test both out.

The NVMe is not the boot device and should get unlocked under windows.

**Comment by hardhub** [comment]
> Smasung 970 Pro NVMe

Correct typo

**Comment by BabaYB** [comment]
Hi @oom-is ,I have the same problem like @Zetanova  had. 
I allways get the resault as:

Scanning for Opal compliant disks
\\.\PhysicalDrive0 No
\\.\PhysicalDrive1 No
\\.\PhysicalDrive2 No
No more disks present ending scan

MY ENV:
windows 7
samsung 970 EVO Plus via USB 3.0 converter

thanks,
Baba_Yb

**Comment by Zetanova** [comment]
@BabaYB USB will most likely not work and RAID driver are not working most of the time. 
Both suppressing the ATA commands to the drive.

**Comment by ayushkumar024** [comment]
Thanks @Zetanova

**Comment by Sed-Research** [comment]
Solutions for external NVME drives across all platforms:

https://github.com/Drive-Trust-Alliance/sedutil/issues/115#issuecomment-751353033

**Comment by Sed-Research** [comment]
> This is a fault in DTA official "vanilla" SEDutil which does not formally support NVMe devices under Windows (and unfortunately is lacking updates since 2017). Please feel free to take a look at the [precompiled binaries in my fork](https://github.com/oom-is/sedutil/releases), or the [original lukefor fork](https://github.com/lukefor/sedutil/tree/windows_nvme) from which I sourced the Windows NVMe patch, or [ChubbyAnt's fork](https://github.com/ChubbyAnt/sedutil/releases) also derived from @lukefor's code, for binaries that do support NVMe on Windows.

This thread contains a precompiled Lukefor executable for Windows which works:

https://github.com/chubbyant/sedutil/issues/2

However @oom-is a small correction to what you wrote, ChubbyAnt's fork does not integrate the lukefor nvme in windows code, on sedutil.com they say they support nvme in windows only by unlocking using PBA first.

**Comment by neo125874** [comment]
@oom-is Hello, would the windows sedutil-integ version suppport nvme psid-revert etc. function, 
or only support scan & query on windows now?
