### ISSUE TITLE
Samsung PM981a support?

### ISSUE THREAD

**Issue by imaginifer123** [Drive-Trust-Alliance/sedutil#328]
Hello, I have Samsung PM981a NVMe drive installed in a PCI-e adapter card. I've tried several forks of the sedutil which should support NVMe but all show that the drive does not support TCG OPAL, even the rescue disks did so.

It is complicated to find out any relevant documentation for the Samsung drive on the internet, but the scarce [finds](https://kc.mcafee.com/corporate/index?page=content&id=KB81136) suggest that the OPAL should be supported. Any ideas why it's not working?

**Comment by tonsui** [comment]
Download Samsung magician tool and check your PM981a status? Maybe you need enable Opal or disable class0 function.

**Comment by imaginifer123** [comment]
Samsung magican says it's an unsupported drive and shows no info. Samsung does not provide customers support for these OEM drives.

**Comment by tonsui** [comment]
Is there a 32-character PSID on the SSD label? Since OEM drives have difference firmware by customer. A few country they don’t want any encrypt function, like AES and TCG Opal.

**Comment by imaginifer123** [comment]
`PSID: 105SJFB3EXB3SHELQWLUF33NXQTWPKCJ`

If it is the case, is there a way how to flash a different FW with Opal support?

**Comment by imaginifer123** [comment]
A have an information that it does not work with PM981 (without -a) either. And according to a datasheet it definitely should! The problem must be with the sedutil and the way how it detects TCG OPAL support. Could someone fix it?

**Comment by Sed-Research** [comment]
A PM981a is one of the SSD's that was successfully working for me, the reason it isn't working for you is very likely because your pci-e adapter card is not able to pass on the Opal commands. If you are referring to a USB adapter card then it's most certainly the reason, if it's an internal adapter card then it's still a possibility though I have not done any testing with these types of adapters. It would be useful to know what chipset your adapter card is using. Please read this comment for further information:

https://github.com/Drive-Trust-Alliance/sedutil/issues/115#issuecomment-751353033

**Comment by imaginifer123** [comment]
> 
> 
> A PM981a is one of the SSD's that was successfully working for me, the reason it isn't working for you is very likely because your pci-e adapter card is not able to pass on the Opal commands. If you are referring to a USB adapter card then it's most certainly the reason, if it's an internal adapter card then it's still a possibility though I have not done any testing with these types of adapters. It would be useful to know what chipset your adapter card is using. Please read this comment for further information:
> 
> [#115 (comment)](https://github.com/Drive-Trust-Alliance/sedutil/issues/115#issuecomment-751353033)

**Comment by imaginifer123** [comment]
Sed-Research: Thanks for your thoughts. As I’ve written above, it’s an internal pci-e card, more specifically [this one](https://www.axagon.eu/en/produkty/pcem2-s).

**Comment by Sed-Research** [comment]
@imaginifer123 It looks like that is a simple m.2 pci adapter without much else going on. It should work with the right sedutil-cli fork.

Oom-is has a windows fork which is pretty much the only one that works well for nvme over pci-e, I expanded on this here:

https://github.com/chubbyant/sedutil/issues/2#issuecomment-869080681

I assume you are using windows because of samsung magician, and so Oom-is should work. If you still can't get it to work the next step is to confirm the drive's Opal capabilities by trying to test it in Linux or PBA (natively or through a virtual machine). If it works there and not in Windows we know where the issue stems from. Another option is to purchase a specific type of usb enclosure which works in windows with pretty much every fork of sedutil and test to make sure the drive is opal capable that way.

More on nvme opal drive support over USB in windows here:

https://github.com/Drive-Trust-Alliance/sedutil/issues/115#issuecomment-751353033
