### ISSUE TITLE
How to give the Range1's access to user1？

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#39]
I want to give the Range1's access to user1.User1 can only manipulate range1.

The following is my step:
first,initialSetup password device
second,enableLockingRange 0 password device
third,setupLockingRange 1 1 2000000 password device
fourth,enableLockingRange 1 password device
fifth,poewer off the device
sixth,poewer on the device
seventh,diseLockingRange 1 password device
eighth,setMBRDone on
To this, I should be able to unlock  LockingRange1,I think.
But I'm puzzled how to use user1 and above LockingRange1 is not unLocking.
Who can answer ,thank you!!!

**Comment by r0m30** [comment]
The code in it's current state doesn't support the ACE.Set commands to grant a user access to a locking range or specifying the user when manipulating the drives.  

On step 7 you use what I think is supposed to be disableLockingrange.  That command stops the drive from locking that range, when you want to unlock a range you should use setLockingRange n RW so that the range relocks when the drive is power cycled.  But again at this time only the Admin1 user is supported.

**Comment by liuligang** [comment]
Thank you very much for @r0m30's help. But I don't understand  what do setupLocking command and enable command  do? if I use these two commands, what  are the phenomenon ?

**Comment by r0m30** [comment]
The enableLockingRange/disableLockingRange commands turn the locking on and off.  The setLockingRange command makes the data accessible until a power cycle. 

Put another way. disableLockingRange makes the data accessible until an EnableLockingRange command is issued and the setLockingRange makes the data accessible until a power cycle.

You may not notice this because the Shadow MBR is also enabled so when you do a power cycle the Shadow MBR hides the data.   You can see this if you boot a USB stick and do a query on the drive, if you look at the Locked parameter it will show the locked state even if the data is obscured by the shadow MBR.

In a single user locking scenario this isn't that important because you have both the ability to set MBRdone and unlock the range but if you were to setup multiple ranges with multiple users you could expose the data in the locking range to someone without the authority to unlock the range.

**Comment by liuligang** [comment]
Hi, @r0m30 
You said "The code in it's current state doesn't support the ACE.Set commands to grant a user access to a locking range or specifying the user when manipulating the drives. "

I'm a little confused by enableuser(argv[opts.password],argv[opts.userid]) command and setupLockingRange(setupLockingRange(opts.lockingrange,atoll(argv[opts.lrstart]),atoll(argv[opts.lrlength]),argv[opts.passwor])) command.

Don't the two commands are not use now, it is for development in the future?

**Comment by liuligang** [comment]
Hi,@r0m30 
Ask again, will  open source code  update? In other words, the function of the code will do more in the furture?

**Comment by liuligang** [comment]
Hi, @r0m30 
I want to know the code in it's current state if  support  add users and access to locking range0?
I see enableuser(argv[opts.password],argv[opts.userid]) command. But I found this command doesn't seem to add users and access to locking range0.

**Comment by r0m30** [comment]
@liuligang 
The setup locking range command allows you to setup locking ranges that can then be managed by the Admin1 user.  
No, there is no support for modifying the ACE tables at this time.  
Yes, the source code will be updated as we expand the use cases that we support, when or if modifying the ACE tables will be added is not known at thins time.

**Comment by liuligang** [comment]
oh， @r0m30 
Thank you for your help.
