### ISSUE TITLE
ran into trouble after enabling bios password on sedutil locked drive

### ISSUE THREAD

**Issue by serektr** [Drive-Trust-Alliance/sedutil#41]
followed the install procedure
rebooted. no PBA showed up, instead i had a no boot device found
i suspect this happened because i used the uefi 64 pba on w7 machine
i was deceived by an hidden option in my bios called compatibility mode that simulates a uefi environment to allow dual booting w7 and w8
anyway i figured i could still use the pba on my usb device, i did and it worked, i got to my desktop no problems.
then i screwed up, enabled bios autentication, figured why the heck not extra layer of security cant be too bad... turns out it was the worst possible thing i could do, enabling bios autentication on a samsung 840 evo compatible system turns on the built in device encryption, found out about this reading about samsung magician security options: OPAL and bios passwords are mutually exclusive and should never be used toghether.

i disabled the additional password immediatly but now neither the PBA on my usb neither the one on my ssd work and windows goes into BSOD midway through the boot process, i suppose the reason for this is the drive is still sedutil locked.

so then i used the rescue image to disable the locking and it did something, now i can boot into safe mode, however whenever i try to boot in normal mode my system crashes like it uses to.

running out of options can anyone help me unfu* my system ?
can i unload the wrong pbaimage from my drive to load the other one ?

**Comment by r0m30** [comment]
Yes, mixing  OPAL and ATA security is a recipe for disaster.
  
Can you tell what mode the drive is in (what is the output of a query) and what does HDParm say about the drive?  

I believe you will have to erase and reset the drive to get is out of the state it is in.  
After making several backups you will probably need to do one or both of an ATA Security Erase using the ATA master password and/or a PSID revert.  The order you'll need to do these in seems to be as much magic as anything.

You're also likely to experience issues finding the master password if it has been set because each motherboard manufacture sets thier own and doesn't like to give it out because it can be used maliciously by malware.  

It's hard to say why the UEFI 64 PBA without knowing how you're bios is set up but I would guess that even if you have a UEFI bios your running in CSM/Legacu mode so you need to use the LinuxBiosPBA.
