### ISSUE TITLE
Testing PBA failed

### ISSUE THREAD

**Issue by zikann** [Drive-Trust-Alliance/sedutil#44]
Tested on:
Lenovo T520
Samsung 850 EVO EMT01B6Q
After entering any fake password in password query, a message flashes followed by reboot. I managed to get the massage by taking a video of the process. Screenshot of the video attached.
![screenshot_2016-05-05-22-26-37](https://cloud.githubusercontent.com/assets/19213556/15056642/e9db5726-1312-11e6-840f-c8e4b36f4f83.png)

**Comment by gomoku** [comment]
Hey zikann, please don't spam nor duplicate threads, since the same topic already exists here: https://github.com/Drive-Trust-Alliance/sedutil/issues/37
Thus let moderators merge this thread with the above one mentioned. And by the way this is the third person has the same problem with LBA...prolly the TEST-PBA wiki guide should be more precisely worded.

**Comment by zikann** [comment]
sorry. Closing - duplicate
