### ISSUE TITLE
revertnoerase can't be run due to SP_BUSY

### ISSUE THREAD

**Issue by Ondjultomte** [Drive-Trust-Alliance/sedutil#461]
root@pve:/# ./sedutil-cli --revertnoerase password /dev/sda
method status code SP_BUSY
Session start failed rc = 3

how can Isolve this issue ? SP_BUSY ?

**Comment by Ondjultomte** [comment]
root@pve:/# ./sedutil-cli --revertnoerase password /dev/sda
method status code NOT_AUTHORIZED
root@pve:/# ./sedutil-cli --revertnoerase password /dev/sda
method status code SP_BUSY
Session start failed rc = 3
root@pve:/# ./sedutil-cli --revertnoerase password /dev/sda
method status code SP_BUSY
Session start failed rc = 3

no luck. 

I want to disable all opal/sed functions but how ?

**Comment by Blacklands** [comment]
(I assume this is an internal drive.) Did you try to completely shut down and restart your system? It seems `SP_BUSY` is usually given if there is already a session going on with the drive that wasn't terminated properly. `sedutil` doesn't have a command to check that, but power-cycling the drive (so system reboot is not enough) should do it.

You might also be unlucky and run into some kind of rare bug. If power-cycling the drive doesn't help, that might be the case?
What drive do you have and how is it connected to the system, just out of curiosity? 

EDIT: Actually I just saw that this starts with `NOT_AUTHORIZED`. (Wrong password?) But you shouldn't really be getting `SP_BUSY` after that unless the session wasn't properly closed. So this might really be some kind of bug. But try the power-cycling first.

Is there important data on the drive you can't lose? Otherwise you could also just go for a PSID revert.

**Comment by Ondjultomte** [comment]
Thank för answering! You were right, power cycling solved it.

**Comment by Ondjultomte** [comment]
No, there was no important data, this was a used drive bought on ebay.
