### ISSUE TITLE
there are a few problems trapped around me about sedutil - cli

### ISSUE THREAD

**Issue by liuligang** [Drive-Trust-Alliance/sedutil#65]
there are a few problems trapped around me about sedutil - cli，I hope to someone help me to answer it.
Thanks first here.

One,
I find after I carried out the following steps:
        --initialSetup password dev
        --enableLockingRange  0  password  dev
        power off.
        power  on.
        --setLockingRange  0  RW  password  dev
        --setMBRDone on password  dev
The ssd disk  is decrypted. But in disk management of my computer, the  SSD disk no allocation until the selected SSD disk do refresh operation will display partition.  At the same time, the SSD will automatically popup has good partition.  I don't know if you have the same problem.
How can direct the popup the SSD disk has  good partition after decryption?

Two,
I still have a little confused is that Why the password be Admin1 password after executing the command of --initialSetup password device. I see the code find it should be SID password.
I don't know where was the Admin1 password change.Why not be enable Admin1?

**Comment by r0m30** [comment]
The first issue is that the OS (Windows?) doesn't recognize that the disk has been unlocked.  You need to tell the OS to rescan the drives.  On windows this can be done with diskpart using the rescan command, or using IOCTL_DISK_UPDATE_PROPERTIES.  It's generally best to unlock internal drives before you boot WIndows because it doesn't give the normal user much if any say about the state of the disks.

The initialsetup "takes ownership" in TCG speak.  This changes the SID password and activates the Locking SP,  when the Locking is initially activated the password for ADMIN1 user in the Locking SP is set to the same value as the SID password.  This behavior is defined in the TCG spec, I can't tell you why they made it that way but it is how they said it should work.
