### ISSUE TITLE
LinuxPBA - Makefile errors

### ISSUE THREAD

**Issue by radmanz** [Drive-Trust-Alliance/sedutil#67]
Hi All,

I've had a pending issue when trying to build LinuxPBA from the command line.
Going off the instructions found @ https://github.com/Drive-Trust-Alliance/sedutil/wiki/Building-sedutil
I conduct the following
cd /sedutil/LinuxPBA
make clean
make CONF=Debug
The make file makes it way through compiling a few files then the compilation is terminated due to the following error returned.

> g++ -m32   -c -g -Werror -DDTADEBUG -I../linux -I../Common -I../Common/pbdkf2 -std=c++11 -MMD -MP -MF "build/Debug/GNU-Linux/_ext/7daaf93a/DtaHashPwd.o.d" -o build/Debug/GNU-Linux/_ext/7daaf93a/DtaHashPwd.o ../Common/DtaHashPwd.cpp
> ../Common/DtaHashPwd.cpp:29:20: fatal error: pbkdf2.h: No such file or directory
>  #include "pbkdf2.h"
>                     ^

I have found that if i update the include path within 'DtaHashPwd.cpp' -> #include "/pbkdf2/pbkdf2.h" it will get past this error. But i don't believe this is a solid fix, as when i observe the /LinuxPBA/nbproject/Makefile-Debug.mk, the -I parameter on 'DtaHashPwd.cpp' is spelt different to the folder. Please see the -I flags below 

> -I../../Common/pbdkf2  ->  -I../../Common/pbkdf2

Am i missing some dependencies or is this a genuine typo?

Once i pass this compilation error, i get yet another error which is:

> make CONF=Debug
> "make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
> make[1]: Entering directory `/home/imon/Documents/Trunks/sedutil/LinuxPBA'
> "make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux/linuxpba
> make[2]: Entering directory`/home/imon/Documents/Trunks/sedutil/LinuxPBA'
> make[2]: **\* No rule to make target `**../Common/pbkdf2/gc-gnulib.c**', needed by`build/Debug/GNU-Linux/_ext/b7b9df0c/gc-gnulib.o'.  Stop.
> make[2]: Leaving directory `/home/imon/Documents/Trunks/sedutil/LinuxPBA'
> make[1]: *** [.build-conf] Error 2
> make[1]: Leaving directory`/home/imon/Documents/Trunks/sedutil/LinuxPBA'
> make: **\* [.build-impl] Error 2

Looking at /pbkdf2/ i cannot find gc-gnulib.c, config.h, gc.h so i copied them from the syslinux.git; syslinux/com32/msedpba/ only to find more errors such as:

> gcc -m32   -c -g -Werror -DDTADEBUG -I../linux -I../Common -I../Common/pbdkf2 -std=c11 -MMD -MP -MF "build/Debug/GNU-Linux/_ext/b7b9df0c/gc-gnulib.o.d" -o build/Debug/GNU-Linux/_ext/b7b9df0c/gc-gnulib.o ../Common/pbkdf2/gc-gnulib.c
> ../Common/pbkdf2/gc-gnulib.c:644:19: error: field ‘sha1Context’ has incomplete type
>    struct sha1_ctx sha1Context;

I tried using netbeans last night on Xubuntu 15.04 to conduct the above, but also returned the same results. After hours of research I found r0m30 uses 14.04, so i thought i'd give it a go within that environment, but still no success.

Any help would be appreciated on getting these compilation issues solved.

I'm using the following to complete the above task:
OS: _Xubuntu 14.04_
Dependencies installed: _apt-get install libc6-dev libncurses5-dev libncursesw5-dev_
GIT: _git clone https://github.com/Drive-Trust-Alliance/sedutil.git_

Thanks in advance =)

**Comment by pgeremia** [comment]
Have you resolved this issue yet?  I am running into the same problem.

**Comment by corporategoth** [comment]
I am having the same issue.  I would love to try and rebuild the image to support my TPM module.

**Comment by pgeremia** [comment]
That is exactly what I want to do.  I want to implement auto boot from TPM for server applications.  If I could get it to build, I could move forward with this.  I was hoping someone from the project would comment with a solution.  If not I may have to just dig in and figure it out myself.

**Comment by radmanz** [comment]
I've been meaning to jump back on to this. I have found another LinuxPBA repo that compiles fine.
It may be an older version, I'm not sure. My plan is to compare the two repo's. This is only a thought, i have not tested and I'm still not sure i understand the whole procedure documented under the build wiki page (which i'd like to contribute to after this is solved).

Here is the repo where LinuxPBA can be built successfully. Hope this helps.
[](https://github.com/JanLuca/sedutil-debian)
Please keep this thread posted if anyone has any success with fixing the issue above, and ill do the same!
@r0m30 - is there any build tips you could give us to resolve this issue?

**Comment by corporategoth** [comment]
@radmanz am I missing something? or did you neglect to include the link?

**Comment by radmanz** [comment]
updated, apologies.

**Comment by pgeremia** [comment]
No thank you for helping out!!  Much appreciated!!!!

**Comment by corporategoth** [comment]
FYI, I forked the project to work on what I've been trying to do.

I got the mainline to compile (ie. the drive-trust-alliance version, not JanLuca's version) by fixing which files it was trying to compile.

Additionally I've been working on setting it up so that it has TPM and USB device auto-unlocking (aka. the bitlockerization of this project).  The code is basically done, but I've not had a chance yet to test it.

But if you're interested, feel free to check it out (even if you don't use the TPM and/or USB key auto-unlock features, it still compiles at least).

If you want to try out the TPM/USB key unlocking stuff, I set it up so that you just have to run a setupautounlock command (instructions in the BUILDING file).  And you specify the TPM slots and/or USB sticks you want to configure for auto unlocking.

It works by storing your unlock password in an encrypted squashfs filesystem (using dm-crypt, though I'm not 100% sure I'm going to keep it, cryptsetup basically has a 1mb overhead for each archive).  For each TPM slot or USB drive you specify, it creates a new key slot on that dm-crypt volume (so that the password to unlock in the TPM and that on the USB device are different).  TPM slots are both set to check all the BIOS-set PCR values (so taking things to a different computer won't work).

On boot it will first check the TPM slot associated for the device, and if it's defined, and can be read, it will read a password from there, and use that to decrypt the dm-crypt, and from there obtain the password to decrypt the SSD.  If we successfully decrypted the SSD using a TPM slot, it will lockout that TPM slot so that it can't be read until a restart.  If the TPM slot is unreadable, it will check any usb devices inserted in the machine that have a vfat or ext* filesystem on them, and mount each one it can access looking for the unlock keyfile.  If it finds it, it will use that to unlock the dm-crypt and as with the TPM version and then unlock the SSD.

I'm mentioning this here because @pgeremia mentioned he was trying to achieve this.

As I said, I've not had a chance to fully test this, as I'm waiting for delivery of new SSDs (the old ones bit the dust at the same time, ugh!).

My fork and branch is https://github.com/corporategoth/sedutil/tree/tpmsupport

**Comment by pgeremia** [comment]
This is excellent.  I will grab and test out!!  Thanks!

**Comment by r0m30** [comment]
OK, sorry it tool so long to respond.  I'm assuming you are working from master?  It looks like when I replaced the pbkdf2 function I didn't update the LinuxPBA project.  If you checkout the latest tag (1.12) it should compile, the differences are mostly Windows and SAS drive related. 

It shouldn't be to difficult to fix.  It's just changing the pbkdf2 filenames and changing the includes.

nice work @corporategoth, I'll try and make some time to look at the code.

**Comment by r0m30** [comment]
Great time for an internet outage.......

I just pushed a fix to master, the PBA should compile now.

**Comment by radmanz** [comment]
confirmed fixed. thanks @r0m30 
dependencies installed under xubuntu release:
libc6-dev-i386 gcc-4.9-multilib g++4.9-multilib libncurses5-dev libncursesw5-dev

**Comment by pgeremia** [comment]
HI @corporategoth.. I have been trying to build your TPM enabled version and there are some build issues.  Most of the problems have been getting the correct packages installed on the system.  But I was wondering what your build environment is?  What OS dist are you using to build the system?  I am using Xubuntu_64.  I can change to whatever makes the most sense.  I went with Xubuntu as that was in the instructions.

**Comment by corporategoth** [comment]
@pgeremia I built that on CentOS, but as I said, I did not get a chance to test it on a live system yet as it turns out that sedutil can't read the stuff it needs through a SAS controller.  But i'll be resuming my effort (also on centos, and arch) once I get the replacement SSDs back from Samsung for the ones that died.

But as for building, it was done on centos (everything DID compile, and the scripts seemed to work)

**Comment by pgeremia** [comment]
@corporategoth Great, I am building up a CentOS 7 VM right now and will let you know how it goes.  Thanks!

**Comment by pgeremia** [comment]
@corporategoth @r0m30 I finally built up a CentOS 7 VM and installed the latest updates and all of the dependent packages.  I carefully followed the build process.  I wrote the Rescue image to a usb flash drive and it will not boot.  But if I grab the Rescue image from the pre-built area, it works.  I am guessing there is something not quite right in my build environment.  

Maybe we could create a set of instructions for creating a build system?  If you have any thoughts on this it would be appreciated.  Thanks!

**Comment by corporategoth** [comment]
@pgeremia I finally have the replacement drives, and I'm working on something now.  The version I'm using now is also centos, but in this case I'm going to be using a yubikey challenge-response as the computer in question does not have a TPM.

Aside from the standard build tools (gcc, libtool, m4, automake, autoconf), you will also need to install the following packages for the PBA to build:
glibc-devel.i686
ncurses-devel
libgcc.i686
ncurses-devel.i686
ncurses-libs.i686
texinfo

There may be more, but I'm still in progress building, I've not yet tried to boot off a PBA yet.  I need to adapt the work I did before for TPM to now also work with a yubikey challenge-response (which means a different set of tools).

**Comment by pgeremia** [comment]
@corporategoth Thank you for the info.  I will try again.  Oh the other question I had is in regards to setting up the TPM.  How did you envision the setup script running?  It has dependencies on TrouSerS correct?  I am almost thinking we should create a Rescue or Setup boot image that has everything you need to write the PBA (sedutil-cli, PBA image and TPM setup script) and access the TPM via TrouSerS.  Does that make sense?  That way you are not dependent on the host OS you are running.

**Comment by corporategoth** [comment]
I posted this in another task, but:

OK, I have re-forked my repo from this.  The code here now works:
https://github.com/corporategoth/sedutil

It will add support for decrypting using a TPM (using the tpm tools from luks-tpm, not trousers), A file on a USB device, or a challenge-response using a yubikey - in any combination.  And the code works because I'm using it myself (right now the only unlock method I'm using on the computer I was developing on is yubikey, but the other unlock methods should work just fine).

It's all been built on centos 7.

**Comment by r0m30** [comment]
This thread went sideways and changed topics, the issue in the title is fixed but there is good info in this thread about using yubikey and the TPM...... what to do?
