### ISSUE TITLE
Suspend

### ISSUE THREAD

**Issue by alfechner** [Drive-Trust-Alliance/sedutil#69]
I realized that suspend is not working if the SED ist encrypted using pre boot authentication. Reason for that is obviously the loss of power of the hard drive. Searching around I realized that a lot of people consider this to be a bug in sedutil. The way I look at it it's rather a technical limitation (also in terms of security) than really a bug.

So I'd like to check if you guys consider this a bug and if you plan to implement/fix it. If so, do you already have any ideas how you could do it? I'm really curious about a solution in terms of security.

**Comment by ZJaume** [comment]
I think the technical limitation is that sedutil can't protect us from the vulnerabilty of sleep mode that is inherent for all Self-Encrypting Drives. I also think the bug is the abscence of the capability of sedutil to let us use sleep mode.
In conclusion, my opinion is that sedutil or the distros should let us use sleep mode independently of that vulnerability.

**Comment by goldcove** [comment]
Is anyone working on a device driver to unlock the disk when resuming from suspend?

**Comment by martin-paulus** [comment]
Since unlocking is dependant on the user inputting a password (and should stay that way imho) you will not be able to develop a device driver to unlock the drive without user intervention.

If you really care more about hibernation than about security then perhaps it is possible to develop a device driver which does not lock the disk upon sleep / power off. However, that defeats the purpose of having disk encryption at all. Because your data would be available in unencrypted form when resuming the device. And thus susceptible to access through alternative boot media. Or even removing the disk and connecting it to another device to access its contents.

**Comment by alfechner** [comment]
I think you mixed things up a little bit. This issue is not about hibernation. 

In case of hibernation I'm not sure if it works with sedutil already or not. After all the state of memory is saved to the hard drive and the computer is powered off. If one turns it on again the OS should be able to restore the memory's state after successfully decrypt the hard drive, right? I guess a reason why people (including me) don't like hibernation on SSD's is the limited number of write accesses. 

In case of suspension the computer is not shut down completely but the hard drive is. So after wake up the memory's state is still there but the access to the hard drive is gone. So in this case a user must obviously provide his/her passphrase in order to unlock it. Sedutil does not provide this functionality and this is what this issue is about.

**Comment by martin-paulus** [comment]
Actually, a hibernated system can only be resumed after access to the disk is restored. In case of Linux, the bootloader and the kernel have to be run before a system can resume. A hibernated system has stored its memory state to disk.

Currently, the disk is locked whenever it loses power and we should keep it that way. Otherwise, one could attack a laptop by just ripping out its battery during operation.

**Comment by r0m30** [comment]
Hibernation does work with sedutil, I use it daily.  The PBA is booted when the system powers up, asks the user for a password and then reboots, the OS then proceeds with it's post hibernation boot process normally.

**Comment by goldcove** [comment]
I **finally** got hibernation to work on my linux/laptop combo after literally months of trying... pesky wlan driver.

Hibernation is an OK substitution for suspend until suspend is supported. It's just too bad that hibernation is so flaky under linux...

**Comment by alfechner** [comment]
As I said: this thread is *not* about hibernation. Hibernation works like a charm with Ubuntu in my case. @r0m30 pointed out how.

I still don't see any proper answer to my question, wondering why this thread is closed :)

**Comment by cristim** [comment]
@alfechner don't worry, the same discussion continued on #90
